### ISSUE TITLE
New font

### ISSUE THREAD

**Issue by lukefretwell** [cnwagwu/cnwagwu.github.io#13]
@cnwagwu did you want to add a different font? If so, pick out the one(s) you want here so we can add and play with the styling:

https://fonts.google.com/

**Comment by cnwagwu** [comment]
Yes the family of fonts I want to pick are [here](https://fonts.google.com/share?selection.family=Open%20Sans%7CPlayfair%20Display:wght@700;900%7CRoboto%20Mono) and their assignments are the following:

- Name Heading: Playfair Display Black
- NAV: Roboto Mono (All Caps) Regular
- Pages Heading: Playfair Display Bold
- Pages Body Text: Open Sans Regular

**Comment by lukefretwell** [comment]
@cnwagwu let's keep the issues open until we've fully hashed out and deployed them.

Added the fonts! I think it would be good for you to fill in front matter content (pages, page descriptions, content below front matter) so we can see what it looks like and tweak the fonts in context of actual content.

Feel free to add comments in this thread if you see anything that you think needs to be tweaked.

Looking good!
