### ISSUE TITLE
Bullet resume page?

### ISSUE THREAD

**Issue by lukefretwell** [cnwagwu/cnwagwu.github.io#15]
Reference: https://chizo.info/resume/

Suggestion: Put the two options in a `<ul>` like:

Formats:

* [Google Doc](https://drive.google.com/file/d/1X1zp3exYGMAeQrSEZAi6eG43i00eylMH/view?usp=sharing)
* [PDF](https://github.com/cnwagwu/cnwagwu.github.io/files/7698002/Nwagwu_Chizobam_Full.CV_2021.pdf)

**Comment by cnwagwu** [comment]
Yes and I was thinking of actually writing out a preview for my resume in case someone doesn't want to open it in another tab/download it but get a quick glance at my experience.
