### ISSUE TITLE
Add Work page

### ISSUE THREAD

**Issue by cnwagwu** [cnwagwu/cnwagwu.github.io#5]
- [x] Work main page
- [x] Work layout page
- [x] Add to homepage
- [x] Sketch of what that page would be
- [x] Design low-fi version for the WORK page
- [x] Backtrack and clearly outline text and files for the Work subPage (for each project) in Notion

**Comment by lukefretwell** [comment]
@cnwagwu ready for you to plug in!

* Main work page: https://chizobamnwagwu.com/work/work1
* Individual work page: https://chizobamnwagwu.com/work/
* The markdown files are [here](https://chizobamnwagwu.com/work/), and you just need to change the names and front matter.

**Comment by cnwagwu** [comment]
Sketches for reference. Will be adding the low-fi version for feedback shortly. 
![image](https://user-images.githubusercontent.com/35706747/145694713-c6f9cd7f-bf24-4703-94d5-2af26195b082.png)
![image](https://user-images.githubusercontent.com/35706747/145694724-63c9f944-6b92-46e0-97e1-b71631796547.png)

**Comment by cnwagwu** [comment]
<img width="1440" alt="Work Page V1" src="https://user-images.githubusercontent.com/35706747/145696565-0d55f4a6-1325-4c38-a71f-74c763462a3f.png">

The first draft of what the WORK could look like. Tried to go with simple cards for showing projects by area of interest. The tagging may not be necessary potentially. The next upload would be for a single work sample. I also shared the link to the Figma file which should show the CSS stylings. Let me know if this is something that could work in our existing layout. I imagine that the tags would be information that is drawing from the front matter and filtering for ones that match that column. Not sure if that is too advanced of a technique for github as well.

**Comment by cnwagwu** [comment]
Okay finally done! Created draft of what A work sample page could be. I don't think I am married to this specific idea but it at least is an early attempt at what it could cool like... 

![Work Page - A work sample V1](https://user-images.githubusercontent.com/35706747/145697083-abe8bc9a-7ee3-408d-aa0d-fc5665b00871.png)

**Comment by lukefretwell** [comment]
Let's discuss on our next call.

**Comment by lukefretwell** [comment]
@cnwagwu for this, let's get a working version going, so all the text and files you would want to display. That way we can build from real data and understand what the front matter would look like as well as how the pages will display.

**Comment by cnwagwu** [comment]
Understood! I will work on the data part instead!

**Comment by cnwagwu** [comment]
Okay so I just shared where I am working on the content with you in Notion so it's clear how I plan on organizing the data and storying the data. Here you can find a layout of what a single work page should look like and the attributes for each page: https://www.notion.so/5923090427a64c1b85795a189804cb63?v=ee4005b0ccfb443dbde5d42d17bff904

**Comment by cnwagwu** [comment]
I will work on filling the rest of the data tomorrow but all the projects that I know for sure I want show are listed there. I have about 3 more academic paper type projects that will also likely need to be formatted differently. Should I just link straight to them? Or simply attempt to provide some context as well?
