### ISSUE TITLE
Show CV on Home page

### ISSUE THREAD

**Issue by cnwagwu** [cnwagwu/cnwagwu.github.io#6]
- [x] Share updated copy of CV

**Comment by lukefretwell** [comment]
@cnwagwu there's now a section on the homepage where you can modify text/link in the page front matter.

**Comment by cnwagwu** [comment]
I left a comment in my commit but to reiterate, wondering if possible for a way to just view the PDF straight in the markdown? Or would that require that I do something else? 

For reference here is my updated 2021 full CV: https://drive.google.com/file/d/1X1zp3exYGMAeQrSEZAi6eG43i00eylMH/view?usp=sharing

**Comment by lukefretwell** [comment]
@cnwagwu I added a few more front matter items so you can link to the icon or have a button or both:

https://chizo.info/

See this code:

```
cv-title: Resume
cv-icon-link-text: Chizobam Nwagwu's CV
cv-icon-link: /resume
cv-link: /resume
```

Here: https://github.com/cnwagwu/cnwagwu.github.io/edit/master/_pages/index.md

It's all conditional, so if you don't want the button, just don't add data to it. Same with any of the other `cv` items.

**Comment by cnwagwu** [comment]
Got it!
